CAREERS = [
    {
        "id": "janitor",
        "name": "Janitor",
        "xp_required": 0,
        "base_pay": 120,
        "skill_required": None,
        "loot_table": [("scrap_metal", 0.35), ("common_pin", 0.12)],
    },
    {
        "id": "barista",
        "name": "Barista",
        "xp_required": 80,
        "base_pay": 220,
        "skill_required": "cooking",
        "loot_table": [("coffee_badge", 0.14), ("rare_cup", 0.08)],
    },
    {
        "id": "developer",
        "name": "Developer",
        "xp_required": 220,
        "base_pay": 420,
        "skill_required": "coding",
        "loot_table": [("circuit_shard", 0.18), ("epic_keyboard", 0.06)],
    },
    {
        "id": "manager",
        "name": "Manager",
        "xp_required": 450,
        "base_pay": 650,
        "skill_required": "leadership",
        "loot_table": [("rare_pin", 0.16), ("epic_tie", 0.07)],
    },
    {
        "id": "ceo",
        "name": "CEO",
        "xp_required": 800,
        "base_pay": 1100,
        "skill_required": "finance",
        "loot_table": [("legendary_seal", 0.08), ("golden_briefcase", 0.04)],
    },
]

SKILLS = {
    "cooking": {"name": "Cooking", "cost": 1200},
    "coding": {"name": "Coding", "cost": 2600},
    "leadership": {"name": "Leadership", "cost": 5000},
    "finance": {"name": "Finance", "cost": 9200},
}

BUSINESSES = {
    "lemonade_stand": {"name": "Lemonade Stand", "cost": 3500, "hourly_income": 120},
    "cafe": {"name": "Cafe", "cost": 16000, "hourly_income": 520},
    "skyscraper": {"name": "Skyscraper", "cost": 95000, "hourly_income": 2400},
}

SHOP_ITEMS = {
    "matcha": {
        "name": "Matcha Powder",
        "cost": 200,
        "desc": "A basic ingredient for soft green desserts.",
        "category": "Pantry",
        "rarity": "Common",
        "type": "item",
    },
    "azuki": {
        "name": "Azuki Beans",
        "cost": 260,
        "desc": "Sweet red bean filling for classic mochi.",
        "category": "Pantry",
        "rarity": "Common",
        "type": "item",
    },
    "rice_flour": {
        "name": "Rice Flour",
        "cost": 320,
        "desc": "The chewy backbone of every mochi batch.",
        "category": "Pantry",
        "rarity": "Common",
        "type": "item",
    },
    "strawberry": {
        "name": "Strawberry Basket",
        "cost": 420,
        "desc": "Bright fruit filling for fresh daifuku.",
        "category": "Produce",
        "rarity": "Common",
        "type": "item",
    },
    "cream": {
        "name": "Whipped Cream",
        "cost": 500,
        "desc": "Cloud-soft topping for luxe treats.",
        "category": "Dairy",
        "rarity": "Common",
        "type": "item",
    },
    "boba": {
        "name": "Boba Pearls",
        "cost": 650,
        "desc": "Chewy pearls for drink and dessert experiments.",
        "category": "Cafe",
        "rarity": "Rare",
        "type": "item",
    },
    "sakura": {
        "name": "Sakura Petals",
        "cost": 900,
        "desc": "Fragrant petals that make seasonal sweets feel rare.",
        "category": "Seasonal",
        "rarity": "Rare",
        "type": "item",
    },
    "yuzu": {
        "name": "Yuzu Zest",
        "cost": 1200,
        "desc": "Citrus sparkle for a sharp premium finish.",
        "category": "Seasonal",
        "rarity": "Rare",
        "type": "item",
    },
    "gold_leaf": {
        "name": "Gold Leaf",
        "cost": 5000,
        "desc": "Pure luxury for over-the-top presentation.",
        "category": "Luxury",
        "rarity": "Epic",
        "type": "item",
    },
    "moon_sugar": {
        "name": "Moon Sugar",
        "cost": 7600,
        "desc": "A glowing sweetener whispered about in dessert lore.",
        "category": "Luxury",
        "rarity": "Legendary",
        "type": "item",
    },
    "dragonfruit": {
        "name": "Dragonfruit Slice",
        "cost": 2100,
        "desc": "Vivid fruit with a dramatic look and mellow taste.",
        "category": "Produce",
        "rarity": "Epic",
        "type": "item",
    },
    "black_sesame": {
        "name": "Black Sesame Paste",
        "cost": 1400,
        "desc": "Nutty filling with a toasty finish.",
        "category": "Pantry",
        "rarity": "Rare",
        "type": "item",
    },
    "padlock": {
        "name": "Padlock",
        "cost": 1800,
        "desc": "Blocks the next robbery attempt against you.",
        "category": "Utility",
        "rarity": "Rare",
        "type": "utility",
    },
    "landmine": {
        "name": "Landmine",
        "cost": 3500,
        "desc": "Punishes the next robber and sends them to the hospital.",
        "category": "Utility",
        "rarity": "Epic",
        "type": "utility",
    },
    "fake_wallet": {
        "name": "Fake Wallet",
        "cost": 2600,
        "desc": "Makes your wallet look empty on profiles.",
        "category": "Utility",
        "rarity": "Rare",
        "type": "utility",
    },
    "basic_crate": {
        "name": "Basic Crate",
        "cost": 1400,
        "desc": "Contains a random collectible with a small rare chance.",
        "category": "Gacha",
        "rarity": "Rare",
        "type": "crate",
    },
    "elite_crate": {
        "name": "Elite Crate",
        "cost": 5200,
        "desc": "Better odds for epic and legendary collectibles.",
        "category": "Gacha",
        "rarity": "Epic",
        "type": "crate",
    },
}

COLLECTIBLES = {
    "common_pin": {"name": "Common Pin", "rarity": "Common"},
    "coffee_badge": {"name": "Coffee Badge", "rarity": "Common"},
    "circuit_shard": {"name": "Circuit Shard", "rarity": "Rare"},
    "rare_cup": {"name": "Rare Tea Cup", "rarity": "Rare"},
    "rare_pin": {"name": "Rare Pin", "rarity": "Rare"},
    "epic_keyboard": {"name": "Epic Keyboard", "rarity": "Epic"},
    "epic_tie": {"name": "Executive Tie", "rarity": "Epic"},
    "legendary_seal": {"name": "Legendary Seal", "rarity": "Legendary"},
    "golden_briefcase": {"name": "Golden Briefcase", "rarity": "Legendary"},
    "scrap_metal": {"name": "Scrap Metal", "rarity": "Common"},
    "golden_shield": {"name": "Golden Shield", "rarity": "Epic"},
}

CRATE_DROPS = {
    "basic_crate": [
        ("common_pin", 0.38),
        ("coffee_badge", 0.28),
        ("scrap_metal", 0.2),
        ("circuit_shard", 0.1),
        ("rare_cup", 0.04),
    ],
    "elite_crate": [
        ("circuit_shard", 0.26),
        ("rare_cup", 0.22),
        ("rare_pin", 0.2),
        ("epic_keyboard", 0.14),
        ("epic_tie", 0.1),
        ("legendary_seal", 0.05),
        ("golden_briefcase", 0.03),
    ],
}

RARITY_STYLES = {
    "Common": "Common",
    "Rare": "Rare",
    "Epic": "Epic",
    "Legendary": "Legendary",
}
